" vim/vimrc - Main Vim configuration
" Requires vim-plug: https://github.com/junegunn/vim-plug

" --- Determine script directory (works even when sourced via VIMINIT) ---
let s:vimdir = expand('<sfile>:p:h')

" --- Set up runtimepath to use our vim directory ---
" Prepend our vim dir and append our after dir for ftplugin
execute 'set runtimepath^=' . s:vimdir
execute 'set runtimepath+=' . s:vimdir . '/after'

" --- Auto-install vim-plug if not present ---
let s:plug_path = s:vimdir . '/autoload/plug.vim'
if empty(glob(s:plug_path))
  silent execute '!curl -fLo ' . s:plug_path . ' --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" --- Plugins ---
call plug#begin(s:vimdir . '/plugged')

" Color scheme
Plug 'tomasiser/vim-code-dark'

" Status line
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Fuzzy finder
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Language support
Plug 'vim-python/python-syntax'

" Utilities
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tell-k/vim-autopep8'

" Git integration
Plug 'airblade/vim-gitgutter'

" Which-key (shows available keybindings)
Plug 'liuchengxu/vim-which-key'

" --- Neovim-only plugins ---
if has('nvim')
    " Colorscheme (treesitter-aware)
    Plug 'catppuccin/nvim', { 'as': 'catppuccin' }

    " Treesitter (better syntax highlighting)
    Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

    " LSP Support
    Plug 'neovim/nvim-lspconfig'

    " Autocompletion
    Plug 'hrsh7th/nvim-cmp'
    Plug 'hrsh7th/cmp-nvim-lsp'
    Plug 'hrsh7th/cmp-buffer'
    Plug 'hrsh7th/cmp-path'
    Plug 'hrsh7th/cmp-cmdline'

    " Snippets (required for nvim-cmp)
    Plug 'L3MON4D3/LuaSnip'
    Plug 'saadparwaiz1/cmp_luasnip'
endif

call plug#end()

" --- General Settings ---
syntax enable
filetype plugin indent on
set encoding=utf-8
set fileencoding=utf-8
set number
set relativenumber
set cursorline
set showmatch
set wildmenu
set wildmode=longest:full,full
set mouse=a
if !has('nvim')
    set ttymouse=sgr
endif
set hidden
set updatetime=300
set signcolumn=yes
set shortmess+=c
set scrolloff=5

" Indentation
set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Search
set incsearch
set hlsearch
set ignorecase
set smartcase

" Line wrapping
set wrap
set linebreak
set textwidth=80

" Backups (disable - use git instead)
set nobackup
set nowritebackup
set noswapfile

" Persistent undo
set undofile
let &undodir = s:vimdir . '/undodir'
if !isdirectory(&undodir)
    call mkdir(&undodir, 'p')
endif

" --- Color Scheme ---
if has('termguicolors')
    set termguicolors
endif
set background=dark
if has('nvim')
    colorscheme catppuccin
else
    colorscheme codedark
    let g:airline_theme = 'codedark'
endif

" --- Leader Key ---
let mapleader = " "

" --- Key Mappings ---

" File navigation (fzf)
nnoremap <Leader>ff :Files<CR>
nnoremap <Leader>fg :GFiles<CR>
nnoremap <Leader>fb :Buffers<CR>
nnoremap <Leader>fc :Rg<CR>
nnoremap <Leader>fh :History<CR>

" Buffer navigation
nnoremap [b :bprevious<CR>
nnoremap ]b :bnext<CR>
nnoremap <Leader>bd :bdelete<CR>

" Clear search highlight
nnoremap <Leader>/ :nohlsearch<CR>

" Quick save and quit
nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>
nnoremap <Leader>x :x<CR>

" System clipboard (Leader+y to copy, Leader+p to paste)
nnoremap <Leader>y "+y
vnoremap <Leader>y "+y
nnoremap <Leader>p "+p
vnoremap <Leader>p "+p
nnoremap <Leader>P "+P

" Window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Move lines up/down in visual mode
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Keep cursor centered when scrolling
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap n nzzzv
nnoremap N Nzzzv

" Visual selection search
vnoremap // y/\V<C-R>=escape(@",'/\')<CR><CR>

" --- Plugin Configurations ---

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline_powerline_fonts = 1

" Python syntax
let g:python_highlight_all = 1

" Autopep8
let g:autopep8_max_line_length = 88
let g:autopep8_disable_show_diff = 1
nnoremap <Leader>ap :Autopep8<CR>

" --- Cursor Shape ---
if has('nvim')
    set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
else
    let &t_SI = "\e[6 q"  " Insert mode: bar
    let &t_EI = "\e[2 q"  " Normal mode: block
    let &t_SR = "\e[4 q"  " Replace mode: underline
endif

" --- Which-Key Configuration ---
let g:which_key_map = {}

" File/Find commands
let g:which_key_map.f = {
    \ 'name': '+file/find',
    \ 'f': 'find files',
    \ 'g': 'git files',
    \ 'b': 'buffers',
    \ 'c': 'search content (rg)',
    \ 'h': 'file history',
    \ }

" Buffer commands
let g:which_key_map.b = {
    \ 'name': '+buffer',
    \ 'd': 'delete buffer',
    \ }

" Quick actions
let g:which_key_map.w = 'save'
let g:which_key_map.q = 'quit'
let g:which_key_map.x = 'save and quit'
let g:which_key_map['/'] = 'clear search highlight'

" Clipboard
let g:which_key_map.y = 'clipboard yank'
let g:which_key_map.p = 'clipboard paste'
let g:which_key_map.P = 'clipboard paste before'

" Autopep8
let g:which_key_map.a = {
    \ 'name': '+actions',
    \ 'p': 'autopep8 format',
    \ }

" LSP (neovim only - configured in lua/nvim-config.lua)
if has('nvim')
    let g:which_key_map.l = {
        \ 'name': '+lsp',
        \ 'r': 'rename',
        \ 'a': 'code action',
        \ 'f': 'format',
        \ 'd': 'diagnostics',
        \ }
endif

" Register which-key (after plugins load)
autocmd! User vim-which-key call which_key#register('<Space>', "g:which_key_map")
nnoremap <silent> <Leader> :<C-u>WhichKey '<Space>'<CR>
vnoremap <silent> <Leader> :<C-u>WhichKeyVisual '<Space>'<CR>
set timeoutlen=500   " Time for mapped sequences (which-key popup)
set ttimeoutlen=10   " Time for terminal key codes (fast Escape)

" --- FZF Shortcut Picker ---
" Define shortcuts as [keys, description, command]
let s:shortcut_list = [
    \ ['ff',  'Find files',              ':Files'],
    \ ['fg',  'Git files',               ':GFiles'],
    \ ['fb',  'Buffers',                 ':Buffers'],
    \ ['fc',  'Search content (ripgrep)', ':Rg'],
    \ ['fh',  'File history',            ':History'],
    \ ['bd',  'Delete buffer',           ':bdelete'],
    \ ['w',   'Save',                    ':w'],
    \ ['q',   'Quit',                    ':q'],
    \ ['x',   'Save and quit',           ':x'],
    \ ['/',   'Clear search highlight',  ':nohlsearch'],
    \ ['ap',  'Autopep8 format',         ':Autopep8'],
    \ ]

function! s:shortcuts_sink(line)
    let l:key = matchstr(a:line, '^\S\+')
    for [keys, desc, cmd] in s:shortcut_list
        if keys ==# l:key
            execute cmd
            return
        endif
    endfor
endfunction

function! s:list_shortcuts()
    let l:result = []
    for [keys, desc, cmd] in s:shortcut_list
        call add(l:result, printf('%-6s  %s', keys, desc))
    endfor
    return l:result
endfunction

command! Shortcuts call fzf#run(fzf#wrap({
    \ 'source': s:list_shortcuts(),
    \ 'sink': function('s:shortcuts_sink'),
    \ 'options': '--prompt="Shortcuts> "'
    \ }))

nnoremap <Leader><Leader> :Shortcuts<CR>

" --- Neovim-specific configuration ---
if has('nvim')
    lua require('nvim-config')
endif
