FROM registry.fedoraproject.org/fedora-toolbox:latest

RUN dnf -y install \
  bat \
  clang \
  g++ \
  htop \
  nodejs \
  nvim \
  sensors \
  timg \
  vim \
  zoxide \
  zsh \
  && dnf clean all


